import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { MenuLeft } from '@/sections/root-layout/menu-left';
import { IoSettingsSharp } from 'react-icons/io5';
import NotificationsActiveIcon from '@mui/icons-material/NotificationsActive';
import { Button } from '@mui/material';
import Image from 'next/image';
import { WidthFull } from '@mui/icons-material';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div
          style={{
            // border: '1px solid black',
            position: 'absolute',
            top: 0,
            left: '280px',
            width: 'calc(100% - 280px)',
            height: '60px',
            display: 'flex',
            justifyContent: 'flex-end',
            paddingLeft: '40px',
            paddingRight: '40px',
          }}
        >
          <div className="header">
            <div className="header-element">
              <NotificationsActiveIcon />
            </div>
            <div className="header-element">
              <Button>
                <Image src="/image/vietnam.png" width={24} height={24} alt="Button Image" />
              </Button>
            </div>
            <div className="header-element">
              <div className="avatar-icon">
                <Button>
                  <span style={{ color: 'white', fontWeight: 'bold', fontSize: '12px' }}>P</span>
                </Button>
              </div>
            </div>
          </div>
        </div>
        <div
          style={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '280px',
            height: '100vh',
            overflow: 'auto',
            scrollbarWidth: 'thin',
          }}
        >
          <MenuLeft />
        </div>
        <div
          style={{
            position: 'absolute',
            top: '60px',
            left: '280px',
            width: 'calc(100% - 280px)',
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
